using DriftLab.Core;
using DriftLab.Protocol;
using DriftLab.Storage;

var tests = new List<(string,Func<Task>)>();
void Test(string name, Action body)=>tests.Add((name,()=>{body();return Task.CompletedTask;}));
void Async(string name,Func<Task> body)=>tests.Add((name,body));
void Check(bool value){if(!value)throw new Exception("Assertion failed");}
void Throws(Action a){try{a();}catch{ return;}throw new Exception("Expected rejection");}
async Task Reject(Func<Task> a){try{await a();}catch{return;}throw new Exception("Expected rejection");}
StickSample[] Samples(Func<int,double> y,int n=801)=>Enumerable.Range(0,n).Select(i=>new StickSample(TimeSpan.FromSeconds(i*8.0/(n-1)),0,y(i),0,0)).ToArray();
var id=new ControllerIdentity("ABC12345678901234",1,2);
var cal=new CalibrationData(Enumerable.Repeat((ushort)32000,12).ToArray());
Test("Analysis normal",()=>Check(DriftAnalyzer.Analyze(Samples(i=>0)).Kind==DriftKind.Normal));
Test("Analysis stable offset",()=>Check(DriftAnalyzer.Analyze(Samples(i=>.06)).Kind==DriftKind.StableOffset));
Test("Analysis progressive up",()=>Check(DriftAnalyzer.Analyze(Samples(i=>-.08*i/800)).Kind==DriftKind.Progressive));
Test("Analysis noise",()=>Check(DriftAnalyzer.Analyze(Samples(i=>i%2==0?.03:-.03)).Kind==DriftKind.Noisy));
Test("Analysis 199 insufficient",()=>Check(DriftAnalyzer.Analyze(Samples(i=>0,199)).Kind==DriftKind.Insufficient));
Test("Analysis gap invalid",()=>{var a=Samples(i=>0).Where(x=>x.Time.TotalSeconds<3||x.Time.TotalSeconds>3.3).ToArray();Check(DriftAnalyzer.Analyze(a).Kind==DriftKind.Insufficient);});
Test("Analysis timestamps invalid",()=>{var a=Samples(i=>0);a[40]=a[30];Check(DriftAnalyzer.Analyze(a).Kind==DriftKind.Insufficient);});
Test("Analysis nonfinite invalid",()=>Check(DriftAnalyzer.Analyze(Samples(i=>double.NaN)).Kind==DriftKind.Insufficient));
Test("Analysis direction dependence",()=>Check(DriftAnalyzer.Combine(new[]{DriftAnalyzer.Analyze(Samples(i=>.06)),DriftAnalyzer.Analyze(Samples(i=>-.06))}).Kind==DriftKind.DirectionDependent));
Test("Protocol wrong header",()=>Throws(()=>FeatureCodec.ReadCalibration(new byte[28])));
Test("Protocol preserves words",()=>{var b=FeatureCodec.Encode(cal.WithCenter(8,32123));Check(b.Length==26&&b[0]==12&&b[1]==1&&b[18]==123&&b[19]==125&&b[22]==0&&b[23]==125);});
Test("Protocol rejects serial path",()=>Check(!FeatureCodec.ValidSerial("../ABC12345678901234")));
Test("Protocol rejects placeholder",()=>Check(!FeatureCodec.ValidSerial("ERROR0000000000")));
Test("Protocol unknown NVS",()=>Check(FeatureCodec.Nv(new byte[]{129,0,0,0,2})==NvStatus.Unknown));
Test("Protocol locked NVS",()=>Check(FeatureCodec.Nv(new byte[]{129,3,3,2,1})==NvStatus.Locked));
Test("Input raw axes",()=>{var b=new byte[64];b[0]=1;b[1]=0;b[2]=255;b[3]=127;b[4]=128;Check(UsbInputDecoder.TryDecode(b,TimeSpan.Zero,out var s,out _)&&s.LX==-1&&s.LY==1&&s.RX<0&&s.RY>0);});
Test("Input Bluetooth rejected",()=>Check(!UsbInputDecoder.TryDecode(new byte[78],TimeSpan.Zero,out _,out _)));
Test("Input short rejected",()=>Check(!UsbInputDecoder.TryDecode(new byte[]{1,2,3},TimeSpan.Zero,out _,out _)));
Test("Input wrong ID",()=>Check(!UsbInputDecoder.TryDecode(new byte[64],TimeSpan.Zero,out _,out _)));
Test("Input secondary collection",()=>Check(!UsbInputDecoder.IsSupported(0x54c,0xce6,1,4,64)));
Test("Input Edge rejected",()=>Check(!UsbInputDecoder.IsSupported(0x54c,0xdf2,1,5,64)));
Test("Guided no return timeout",()=>{var g=new GuidedTest(1);for(int i=0;i<1002;i++)g.Accept(new(TimeSpan.FromSeconds(i*.01),0,0,0,0));g.Accept(new(TimeSpan.FromSeconds(10.1),0,1,0,0));g.Accept(new(TimeSpan.FromSeconds(26),0,1,0,0));Check(g.Failed);});
Test("Guided deliberate movement invalidates",()=>{var g=new GuidedTest(1);for(int i=0;i<1002;i++)g.Accept(new(TimeSpan.FromSeconds(i*.01),0,0,0,0));g.Accept(new(TimeSpan.FromSeconds(10.1),0,1,0,0));g.Accept(new(TimeSpan.FromSeconds(10.2),0,0,0,0));g.Accept(new(TimeSpan.FromSeconds(10.8),0,0,0,0));g.Accept(new(TimeSpan.FromSeconds(11),0,.7,0,0));Check(g.RetryNeeded);});
Test("Verification incomplete cannot save",()=>{var normal=DriftAnalyzer.Analyze(Samples(i=>0));var b=new GuidedTestResult(1,normal,new[]{normal});Check(!VerificationPolicy.Evaluate(b,b,new RangeCheckResult(true)).CanSave);});
Test("Verification other generation",()=>{var normal=DriftAnalyzer.Analyze(Samples(i=>0));var a=new GuidedTestResult(1,normal,Enumerable.Repeat(normal,6).ToArray());var b=a with{Generation=2};Check(!VerificationPolicy.Evaluate(a,b,new(true)).CanSave);});
Test("Verification bad right",()=>{var a=Samples(i=>0).Select(s=>s with{RX=.1}).ToArray();var bad=DriftAnalyzer.Analyze(a);var t=new GuidedTestResult(1,bad,Enumerable.Repeat(bad,6).ToArray());Check(!VerificationPolicy.Evaluate(t,t,new(true)).CanSave);});
Test("Verification reduced range",()=>{var n=DriftAnalyzer.Analyze(Samples(i=>0));var t=new GuidedTestResult(1,n,Enumerable.Repeat(n,6).ToArray());Check(!VerificationPolicy.Evaluate(t,t,new(false)).CanSave);});
Async("Storage integrity and identity",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var repo=new BackupRepository(root);var b=CalibrationBackup.Create(id,cal,"Initial");await repo.SaveAsync(b,default);var path=Directory.GetFiles(root,"*.json",SearchOption.AllDirectories).Single();var read=await repo.ReadAsync(path,default);BackupValidator.Validate(read,id);Throws(()=>BackupValidator.Validate(read,id with{Firmware=2}));Throws(()=>BackupValidator.Validate(read with{Hash=new string('0',64)},id));}finally{Directory.Delete(root,true);}});
Async("Storage duplicate keys rejected",async()=>{var p=Path.GetTempFileName();try{await File.WriteAllTextAsync(p,"{\"Version\":1,\"Version\":1}");await Reject(()=>new BackupRepository(Path.GetTempPath()).ReadAsync(p,default));}finally{File.Delete(p);}});
Async("Storage overflow rejected",async()=>{var p=Path.GetTempFileName();try{var s=System.Text.Json.JsonSerializer.Serialize(CalibrationBackup.Create(id,cal,"Initial")).Replace("32000","65536");await File.WriteAllTextAsync(p,s);await Reject(()=>new BackupRepository(Path.GetTempPath()).ReadAsync(p,default));}finally{File.Delete(p);}});
Async("Storage disk failure",async()=>{var p=Path.GetTempFileName();try{await Reject(()=>new BackupRepository(p).SaveAsync(CalibrationBackup.Create(id,cal,"Initial"),default));Check(File.Exists(p));}finally{File.Delete(p);}});
Async("Feature timeout blocks another call",async()=>{var gate=new FeatureTransferGate(TimeSpan.FromMilliseconds(20));var stop=new TaskCompletionSource<byte[]>();await Reject(()=>gate.RunAsync(()=>stop.Task,default));int calls=0;await Reject(()=>gate.RunAsync(()=>{calls++;return Task.FromResult(Array.Empty<byte>());},default));Check(calls==0);stop.SetResult([]);});
Async("Correction both feedback signs",async()=>{foreach(var slope in new[]{.0005,-.0005}){var fake=new FakeCorrection(cal,slope);var stable=DriftAnalyzer.Analyze(Samples(i=>.06));var r=await CenterCorrector.CorrectAsync(cal,stable,fake,default);Check(r.Converged&&Math.Abs(fake.Error)<.02&&r.Data.Values[10]==32000&&r.Data.Values[0]==32000);}});
Async("Correction plateau rollback",async()=>{var f=new FakeCorrection(cal,0);var r=await CenterCorrector.CorrectAsync(cal,DriftAnalyzer.Analyze(Samples(i=>.06)),f,default);Check(!r.Converged&&f.Data.SameAs(cal));});
Async("Correction refuses progressive",async()=>{var f=new FakeCorrection(cal,.0005);await Reject(()=>CenterCorrector.CorrectAsync(cal,DriftAnalyzer.Analyze(Samples(i=>-.08*i/800)),f,default));Check(f.Writes==0);});
Async("Controller temporary readback",async()=>{var f=new FakeHid(cal);var c=new DualSenseController(f);await c.WriteTemporaryAsync(cal.WithCenter(9,32100),default);Check(f.Data.Values[9]==32100&&f.Status==NvStatus.Locked);});
Async("Controller unlocked blocks temporary",async()=>{var f=new FakeHid(cal){Status=NvStatus.Unlocked};await Reject(()=>new DualSenseController(f).WriteTemporaryAsync(cal.WithCenter(9,32020),default));Check(f.Data.SameAs(cal));});
Async("Controller save locks after fault",async()=>{var f=new FakeHid(cal){FailUnlock=true};await Reject(()=>new DualSenseController(f).SavePermanentAsync(default));Check(f.LockAttempt&&f.Status==NvStatus.Locked);});
Async("Controller failed lock cannot succeed",async()=>{var f=new FakeHid(cal){FailLock=true};await Reject(()=>new DualSenseController(f).SavePermanentAsync(default));Check(f.LockAttempt);});
Async("Controller invalid readback rejected",async()=>{var f=new FakeHid(cal){IgnoreWrite=true};await Reject(()=>new DualSenseController(f).WriteTemporaryAsync(cal.WithCenter(9,32100),default));});
Test("Session permissions block expired proof",()=>{var a=new SessionState{Connected=true,Verified=true};Check(a.CanSave);a.Invalidate();Check(!a.CanSave);});
Test("Session persistent blocks closing/cancel",()=>{var a=new SessionState{Connected=true,Verified=true,Busy=true,IsPersistentWrite=true};Check(!a.CanSave&&!a.CanRestore&&!a.CanReboot&&!a.CanCancel&&!a.CanClose);});
Async("Session save requires proof",async()=>{var io=new FakeInteraction();var s=new ControllerSession(new DualSenseController(new FakeHid(cal)),id,new BackupRepository(Path.GetTempPath()),io);await Reject(()=>s.SaveAsync(default));Check(!s.State.CanSave);});
Async("Session disconnect invalidates restore proof",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var s=new ControllerSession(new DualSenseController(new FakeHid(cal)),id,new BackupRepository(root),new FakeInteraction());await s.RestoreAsync(CalibrationBackup.Create(id,cal,"Initial"),default);Check(s.State.CanSave);s.Invalidate();await Reject(()=>s.SaveAsync(default));Check(!s.State.CanSave);}finally{Directory.Delete(root,true);}});
Async("Session wrong controller rejected before restore",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));var f=new FakeHid(cal);try{var s=new ControllerSession(new DualSenseController(f),id,new BackupRepository(root),new FakeInteraction());await Reject(()=>s.RestoreAsync(CalibrationBackup.Create(id with{Serial="XYZ12345678901234"},cal,"Initial"),default));Check(f.Data.SameAs(cal));}finally{if(Directory.Exists(root))Directory.Delete(root,true);}});
Async("Session duplicate operations cannot run",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));var io=new FakeInteraction{PendingConfirmation=new TaskCompletionSource<bool>()};try{var s=new ControllerSession(new DualSenseController(new FakeHid(cal)),id,new BackupRepository(root),io);var first=s.RestoreAsync(CalibrationBackup.Create(id,cal,"Initial"),default);await Task.Delay(10);await Reject(()=>s.RebootAsync(default));io.PendingConfirmation.SetResult(false);await first;}finally{if(Directory.Exists(root))Directory.Delete(root,true);}});
Async("Session marks expected disconnect before reboot",async()=>{var io=new FakeInteraction();var f=new FakeHid(cal);f.RebootHook=()=>Check(io.Rebooting);var s=new ControllerSession(new DualSenseController(f),id,new BackupRepository(Path.GetTempPath()),io);await s.RebootAsync(default);Check(!io.Rebooting&&s.State.Connected);});
Async("Review full live guided trace completes",async()=>{var channel=System.Threading.Channels.Channel.CreateUnbounded<StickSample>();double t=0;void Push(double x,double y){channel.Writer.TryWrite(new(TimeSpan.FromSeconds(t),x,y,0,0));t+=.01;}
 for(int i=0;i<1002;i++)Push(0,0);
 foreach(var (x,y) in new(double,double)[]{(0,1),(0,1),(0,1),(0,-1),(1,0),(-1,0)}){Push(x,y);for(int i=0;i<860;i++)Push(0,0);}
 channel.Writer.TryComplete();int updates=0;var result=await SampleAcquisition.GuidedAsync(channel.Reader,44,(_,_)=>updates++,(_,_)=>Task.FromResult(false),default);Check(result.Generation==44&&result.Cycles.Count==6&&result.Overall.Kind==DriftKind.Normal&&updates>100);
});
Async("Review expiry while confirmation pending blocks flash",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var time=new ManualClock();var f=new FakeHid(cal);var io=new FakeInteraction();var s=new ControllerSession(new DualSenseController(f),id,new BackupRepository(root),io,time);await s.RestoreAsync(CalibrationBackup.Create(id,cal,"Initial"),default);io.ConfirmationHook=()=>time.Advance(TimeSpan.FromMinutes(11));await Reject(()=>s.SaveAsync(default));Check(!f.LockAttempt&&!s.State.CanSave);}finally{Directory.Delete(root,true);}});
Async("Review missing reboot evidence cannot confirm persistence",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var io=new FakeInteraction{ResetObserved=false};var s=new ControllerSession(new DualSenseController(new FakeHid(cal)),id,new BackupRepository(root),io);await s.RestoreAsync(CalibrationBackup.Create(id,cal,"Initial"),default);await Reject(()=>s.SaveAsync(default));Check(!s.State.Connected&&!s.State.CanSave);}finally{Directory.Delete(root,true);}});
Async("Review validated restore saves and confirms",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var f=new FakeHid(cal);var io=new FakeInteraction();var s=new ControllerSession(new DualSenseController(f),id,new BackupRepository(root),io);await s.RestoreAsync(CalibrationBackup.Create(id,cal,"Initial"),default);await s.SaveAsync(default);Check(f.LockAttempt&&s.State.Connected&&s.LatestBackup?.Kind=="Restored"&&!s.State.CanSave&&!io.Rebooting);}finally{Directory.Delete(root,true);}});
Async("Session full automatic correction and verified save gate",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var f=new FakeHid(cal);var io=new FakeInteraction();double Error()=>.06+(f.Data.Values[9]-32000)*.0005;io.Guided=g=>{var r=DriftAnalyzer.Analyze(Samples(i=>Error()));return new(g,r,Enumerable.Repeat(r,6).ToArray());};io.Fresh=_=>Enumerable.Range(0,101).Select(i=>new StickSample(TimeSpan.FromSeconds(i*.005),0,Error(),0,0)).ToArray();var s=new ControllerSession(new DualSenseController(f),id,new BackupRepository(root),io);await s.RunAutoAsync(default);Check(s.State.CanSave&&s.State.Verified&&Math.Abs(Error())<.02&&f.Data.Values[8]==32000&&f.Data.Values[10]==32000&&!f.LockAttempt);}finally{Directory.Delete(root,true);}});
Async("Session cancel during flash still completes lock",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{using var stop=new CancellationTokenSource();var f=new FakeHid(cal){UnlockHook=()=>stop.Cancel()};var s=new ControllerSession(new DualSenseController(f),id,new BackupRepository(root),new FakeInteraction());await s.RestoreAsync(CalibrationBackup.Create(id,cal,"Initial"),default);await s.SaveAsync(stop.Token);Check(f.LockAttempt&&stop.IsCancellationRequested&&s.LatestBackup?.Kind=="Restored");}finally{Directory.Delete(root,true);}});
Async("Session wrong persistent readback remains uncertain",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var io=new FakeInteraction{ReconnectData=cal.WithCenter(9,32300)};var s=new ControllerSession(new DualSenseController(new FakeHid(cal)),id,new BackupRepository(root),io);await s.RestoreAsync(CalibrationBackup.Create(id,cal,"Initial"),default);await Reject(()=>s.SaveAsync(default));Check(!s.State.Connected&&s.LatestBackup?.Kind=="Initial");}finally{Directory.Delete(root,true);}});
Async("Session generation changed during full test cannot authorize",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var io=new FakeInteraction();var f=new FakeHid(cal);var s=new ControllerSession(new DualSenseController(f),id,new BackupRepository(root),io);io.Guided=g=>{s.Invalidate();var normal=DriftAnalyzer.Analyze(Samples(i=>0));return new(g,normal,Enumerable.Repeat(normal,6).ToArray());};await Reject(()=>s.RunAutoAsync(default));Check(!s.State.CanSave&&!f.LockAttempt&&f.Data.SameAs(cal));}finally{Directory.Delete(root,true);}});
StickSample[] RawSamples(Func<int,byte> rawY,int n=801)=>Enumerable.Range(0,n).Select(i=>{var b=new byte[64];b[0]=1;b[1]=128;b[2]=rawY(i);b[3]=128;b[4]=128;UsbInputDecoder.TryDecode(b,TimeSpan.FromSeconds(i*8d/(n-1)),out var sample,out _);return sample;}).ToArray();
Test("Precision detects sub-two-percent stable offset",()=>Check(DriftAnalyzer.Analyze(RawSamples(i=>129)).Kind==DriftKind.StableOffset));
Test("Precision detects two-code microtremor",()=>Check(DriftAnalyzer.Analyze(RawSamples(i=>(byte)(i%2==0?127:129))).Kind.ToString()=="MicroTremor"));
Test("Precision preserves one-code quantization",()=>Check(DriftAnalyzer.Analyze(RawSamples(i=>(byte)(i%2==0?127:128))).Kind==DriftKind.Normal));
Test("Precision catches isolated spike missed by percentiles",()=>Check(DriftAnalyzer.Analyze(RawSamples(i=>(byte)(i==400?138:128))).Kind.ToString()=="Spikes"));
Test("Precision detects slow small drift",()=>Check(DriftAnalyzer.Analyze(RawSamples(i=>(byte)(i<100?(i%2==0?127:128):126),201)).Kind==DriftKind.Progressive));
Test("Precision right microtremor blocks verification",()=>{var s=RawSamples(i=>128).Select((v,i)=>v with{RX=i%2==0?-1d/255:3d/255}).ToArray();var r=DriftAnalyzer.Analyze(s);Check(!r.RightNormal&&r.Kind.ToString()=="MicroTremor");});
Async("Precision corrects small stable residual",async()=>{var f=new FakeCorrection(cal,.0005);await f.WriteTemporaryAsync(cal.WithCenter(9,31904),default);var start=f.Data;var r=await CenterCorrector.CorrectAsync(start,DriftAnalyzer.Analyze(Samples(i=>.012)),f,default);Check(r.Converged&&Math.Abs(f.Error)<=.00393);});
Test("Precision small oscillation cannot enable save",()=>{var r=DriftAnalyzer.Analyze(RawSamples(i=>(byte)(i%2==0?127:129)));var t=new GuidedTestResult(1,r,Enumerable.Repeat(r,6).ToArray());Check(!VerificationPolicy.Evaluate(t,t,new(true)).CanSave);});
Test("Precision catches small three-code isolated spike",()=>Check(DriftAnalyzer.Analyze(RawSamples(i=>(byte)(i==400?131:128))).Kind==DriftKind.Spikes));
Async("Precision correction with quantized USB feedback",async()=>{foreach(var slope in new[]{.0003,-.0003}){var f=new FakeCorrection(cal,slope,true);var r=await CenterCorrector.CorrectAsync(cal,DriftAnalyzer.Analyze(Samples(i=>f.ReportedError)),f,default);Check(r.Converged&&Math.Abs(f.ReportedError)<=SignalLimits.TargetCenter&&r.Data.Values[10]==32000);}});
Test("Precision combined diagnostics retain every cycle spike",()=>{var a=DriftAnalyzer.Analyze(RawSamples(i=>(byte)(i==400?131:128)));var b=DriftAnalyzer.Analyze(RawSamples(i=>(byte)(i==400?138:128)));var r=DriftAnalyzer.Combine(new[]{a,b});Check(r.Kind==DriftKind.Spikes&&r.Axes[1].SpikeCount==2&&r.Axes[1].PeakDeviation==b.Axes[1].PeakDeviation&&r.Count==1602);});
Test("Precision range rejects old loose center tolerance",()=>{var r=new RangeCapture();r.Accept(new(TimeSpan.Zero,-1,-1,-1,-1));r.Accept(new(TimeSpan.FromSeconds(.01),1,1,1,1));for(int i=0;i<101;i++)r.Accept(new(TimeSpan.FromSeconds(.02+i*.01),0,.012,0,0));Check(!r.Passed);for(int i=0;i<101;i++)r.Accept(new(TimeSpan.FromSeconds(1.04+i*.01),0,1d/255,0,0));Check(r.Passed);});
Async("Precision right offset requires both-center confirmation",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{int confirmations=0;var f=new FakeHid(cal);var io=new FakeInteraction{PendingConfirmation=new TaskCompletionSource<bool>(),ConfirmationHook=()=>confirmations++};io.PendingConfirmation.SetResult(false);io.Guided=g=>{var r=DriftAnalyzer.Analyze(RawSamples(i=>128).Select(v=>v with{RX=3d/255}).ToArray());return new(g,r,Enumerable.Repeat(r,6).ToArray());};var s=new ControllerSession(new DualSenseController(f),id,new BackupRepository(root),io);await s.RunAutoAsync(default);Check(confirmations==1&&f.CenterCommands==0&&f.Data.SameAs(cal)&&!s.State.CanSave);}finally{Directory.Delete(root,true);}});
Async("Precision persisting tremor rolls back without save",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var f=new FakeHid(cal);var io=new FakeInteraction();io.Guided=g=>{var r=DriftAnalyzer.Analyze(RawSamples(i=>(byte)(i%2==0?127:129)));return new(g,r,Enumerable.Repeat(r,6).ToArray());};var s=new ControllerSession(new DualSenseController(f),id,new BackupRepository(root),io);await s.RunAutoAsync(default);Check(s.After?.Overall.Kind==DriftKind.MicroTremor&&f.CenterCommands==3&&f.Data.SameAs(cal)&&!s.State.CanSave&&!f.LockAttempt);}finally{Directory.Delete(root,true);}});
Test("Precision paired tails cannot hide spikes or enable save",()=>{for(int axis=0;axis<4;axis++){var samples=RawSamples(i=>128);for(int i=0;i<48;i++){int index=100+i*12;double value=i%2==0?-5d/255:7d/255;samples[index]=axis switch{0=>samples[index] with{LX=value},1=>samples[index] with{LY=value},2=>samples[index] with{RX=value},_=>samples[index] with{RY=value}};}var r=DriftAnalyzer.Analyze(samples);var t=new GuidedTestResult(1,r,Enumerable.Repeat(r,6).ToArray());Check(r.Axes[axis].Spread==0&&r.Axes[axis].SpikeCount==48&&r.Kind==DriftKind.Spikes&&!VerificationPolicy.Evaluate(t,t,new(true)).CanSave);}});
Async("Precision small-offset quantized plateaus stay correctable",async()=>{foreach(var (offset,sensitivity) in new(double,double)[]{(.0153,.0003),(-.0153,.0003),(.0149,.0003),(.0119,.0003),(.009,.00004),(.008,.000006),(-.008,.000006)})foreach(var sign in new[]{-1,1}){var f=new FakeCorrection(cal,sensitivity*sign,true,offset);var r=await CenterCorrector.CorrectAsync(cal,DriftAnalyzer.Analyze(Samples(i=>f.ReportedError)),f,default);Check(r.Converged&&Math.Abs(f.ReportedError)<=SignalLimits.TargetCenter&&Math.Abs(r.Data.Values[9]-32000)<=500&&r.Data.Values[8]==32000&&r.Data.Values[10]==32000);}});
Async("Precision correction respects ushort boundary centers",async()=>{foreach(var (origin,slope) in new(ushort,double)[]{(0,-.0005),(65535,.0005)}){var start=cal.WithCenter(9,origin);var f=new FakeCorrection(start,slope,true,.06,origin);var r=await CenterCorrector.CorrectAsync(start,DriftAnalyzer.Analyze(Samples(i=>f.ReportedError)),f,default);Check(r.Converged&&Math.Abs(f.ReportedError)<=SignalLimits.TargetCenter&&Math.Abs(r.Data.Values[9]-origin)<=500&&r.Data.Values.Where((v,i)=>i!=9).SequenceEqual(start.Values.Where((v,i)=>i!=9)));}});
StickSample[] HardTrace(Func<int,double> y)=>Enumerable.Range(0,1501).Select(i=>new StickSample(TimeSpan.FromSeconds(i*.01),0,y(i),0,0)).ToArray();
Test("Hard detect ignores normal one-code USB quantization",()=>{var r=TremorAnalyzer.Analyze(HardTrace(i=>i%2==0?-1d/255:1d/255),TimeSpan.FromSeconds(15));Check(r.Valid&&!r.HasTremor&&!r.HasInstability);});
Test("Hard detect sees two-code oscillation",()=>{var r=TremorAnalyzer.Analyze(HardTrace(i=>i%2==0?-1d/255:3d/255),TimeSpan.FromSeconds(15));Check(r.Valid&&r.HasTremor&&r.Axes[1].RapidChanges>1000);});
Test("Hard detect sees isolated spikes",()=>{var r=TremorAnalyzer.Analyze(HardTrace(i=>i==500?7d/255:1d/255),TimeSpan.FromSeconds(15));Check(r.Valid&&r.HasTremor&&r.SpikeCount>0);});
Test("Hard detect catches stationary offset",()=>{var r=TremorAnalyzer.Analyze(HardTrace(i=>.04),TimeSpan.FromSeconds(15));Check(r.Valid&&r.HasOffset&&r.HasInstability&&!r.HasTremor);});
Test("Hard detect rejects hand movement",()=>{var r=TremorAnalyzer.Analyze(HardTrace(i=>i==500?.6:0),TimeSpan.FromSeconds(15));Check(!r.Valid);});
Test("Hard detect rejects incomplete trace",()=>{var r=TremorAnalyzer.Analyze(HardTrace(i=>0).Take(800).ToArray(),TimeSpan.FromSeconds(15));Check(!r.Valid);});
Async("Hard detect blocks save when tremor remains",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var f=new FakeHid(cal);var io=new FakeInteraction();io.Guided=g=>{var r=DriftAnalyzer.Analyze(RawSamples(i=>f.CenterCommands==0?(byte)(i%2==0?127:129):(byte)128));return new(g,r,Enumerable.Repeat(r,6).ToArray());};io.Fresh=_=>HardTrace(i=>i%2==0?-1d/255:3d/255);var session=new ControllerSession(new DualSenseController(f),id,new BackupRepository(root),io);await session.RunHardDetectAsync(default);Check(session.HardBefore?.HasTremor==true&&session.HardAfter?.HasTremor==true&&!session.State.CanSave&&f.Data.SameAs(cal)&&!f.LockAttempt);}finally{Directory.Delete(root,true);}});
Async("Hard detect refuses unchanged calibration",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var f=new FakeHid(cal);var io=new FakeInteraction();io.Guided=g=>{var r=DriftAnalyzer.Analyze(RawSamples(i=>f.CenterCommands==0?(byte)(i%2==0?127:129):(byte)128));return new(g,r,Enumerable.Repeat(r,6).ToArray());};io.Fresh=_=>HardTrace(i=>f.CenterCommands==0?(i%2==0?-1d/255:3d/255):0);var session=new ControllerSession(new DualSenseController(f),id,new BackupRepository(root),io);await session.RunHardDetectAsync(default);Check(session.HardBefore?.HasTremor==true&&session.HardAfter?.HasTremor==false&&!session.State.CanSave&&f.Data.SameAs(cal));}finally{Directory.Delete(root,true);}});
Async("Hard detect only enables save after real parameter change and clean trace",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var f=new FakeHid(cal);f.CenterHook=()=>f.Data=f.Data.WithCenter(8,32001);var io=new FakeInteraction();io.Guided=g=>{var r=DriftAnalyzer.Analyze(RawSamples(i=>f.CenterCommands==0?(byte)(i%2==0?127:129):(byte)128));return new(g,r,Enumerable.Repeat(r,6).ToArray());};io.Fresh=_=>HardTrace(i=>f.CenterCommands==0?(i%2==0?-1d/255:3d/255):0);var session=new ControllerSession(new DualSenseController(f),id,new BackupRepository(root),io);await session.RunHardDetectAsync(default);Check(session.HardBefore?.HasTremor==true&&session.HardAfter?.HasInstability==false&&session.State.CanSave&&f.Data.Values[8]==32001&&!f.LockAttempt);}finally{Directory.Delete(root,true);}});
Test("Language default guided instructions are English",()=>Check(new GuidedTest(1).Instruction=="Leave both sticks untouched for 10 seconds."));
Test("Language guided move direction is English",()=>{var g=new GuidedTest(1);for(int i=0;i<1002;i++)g.Accept(new(TimeSpan.FromSeconds(i*.01),0,0,0,0));Check(g.Instruction=="Move the LEFT stick fully down (1/6).");});
Async("Language save warning retains English power precautions",async()=>{var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var io=new FakeInteraction();var s=new ControllerSession(new DualSenseController(new FakeHid(cal)),id,new BackupRepository(root),io);await s.RestoreAsync(CalibrationBackup.Create(id,cal,"Initial"),default);await s.SaveAsync(default);Check(io.LastConfirmation.Contains("INTERNAL battery")&&io.LastConfirmation.Contains("Do not disconnect or close")&&io.LastConfirmation.Contains("old drift"));}finally{Directory.Delete(root,true);}});
Test("Language Italian guided instructions remain available",()=>{try{AppText.Select(AppLanguage.Italian);var g=new GuidedTest(1);Check(g.Instruction=="Lascia entrambi gli stick liberi per 10 secondi.");for(int i=0;i<1002;i++)g.Accept(new(TimeSpan.FromSeconds(i*.01),0,0,0,0));Check(g.Instruction=="Porta lo stick SINISTRO tutto in basso (1/6).");}finally{AppText.Select(AppLanguage.English);}});
Test("Language selection preserves existing backup integrity",()=>{try{AppText.Select(AppLanguage.English);var backup=CalibrationBackup.Create(id,cal,"Initial");var json=System.Text.Json.JsonSerializer.Serialize(backup);AppText.Select(AppLanguage.Italian);Check(backup.Hash==CalibrationBackup.Digest(backup)&&System.Text.Json.JsonSerializer.Serialize(backup)==json&&backup.Kind=="Initial");BackupValidator.Validate(backup,id);Check(AppText.Format("Deriva SX {0:0.00}% / DX {1:0.00}% · oscillazione SX {2:0.00}% / DX {3:0.00}% · picco {4:0.00}% · campioni con picchi {5}",1.25,0,0,0,0,0).Contains("1,25%"));}finally{AppText.Select(AppLanguage.English);}});
Async("Language both-stick warning preserves scope and wear limit",async()=>{try{foreach(var language in new[]{AppLanguage.English,AppLanguage.Italian}){AppText.Select(language);var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString("N"));try{var io=new FakeInteraction{PendingConfirmation=new TaskCompletionSource<bool>()};io.PendingConfirmation.SetResult(false);io.Guided=g=>{var r=DriftAnalyzer.Analyze(RawSamples(i=>(byte)(i%2==0?127:129)));return new(g,r,Enumerable.Repeat(r,6).ToArray());};var f=new FakeHid(cal);var session=new ControllerSession(new DualSenseController(f),id,new BackupRepository(root),io);await session.RunAutoAsync(default);Check(io.LastConfirmation.Contains(language==AppLanguage.English?"ONE temporary center calibration of BOTH sticks":"UNA calibrazione temporanea del centro di ENTRAMBI gli stick")&&io.LastConfirmation.Contains(language==AppLanguage.English?"cannot repair wear":"non ripara l'usura")&&f.Data.SameAs(cal)&&!session.State.CanSave);}finally{Directory.Delete(root,true);}}}finally{AppText.Select(AppLanguage.English);}});
var selected=tests.Where(x=>args.Length==0||x.Item1.StartsWith(args[0],StringComparison.OrdinalIgnoreCase)).ToList();int failures=0;
foreach(var (name,body) in selected){try{await body();Console.WriteLine("PASS "+name);}catch(Exception e){failures++;Console.WriteLine("FAIL "+name+": "+e.Message);}}
Console.WriteLine($"{selected.Count-failures}/{selected.Count} passed");return failures==0&&selected.Count>0?0:1;

sealed class FakeCorrection(CalibrationData original,double slope,bool quantized=false,double baseError=.06,int referenceCenter=32000):ICalibrationSession
{
 public CalibrationData Data=original;public int Writes;public double Error=>baseError+(Data.Values[9]-referenceCenter)*slope;
 public double ReportedError=>quantized?(Math.Round(127.5+Error*127.5)-127.5)/127.5:Error;
 public Task WriteTemporaryAsync(CalibrationData data,CancellationToken ct){Data=data;Writes++;return Task.CompletedTask;}
 public Task<IReadOnlyList<StickSample>> GetFreshSamplesAsync(TimeSpan duration,CancellationToken ct)=>Task.FromResult<IReadOnlyList<StickSample>>(Enumerable.Range(0,101).Select(i=>new StickSample(TimeSpan.FromSeconds(i*.005),0,ReportedError,0,0)).ToArray());
}
sealed class FakeHid(CalibrationData initial):IHidTransport
{
 public CalibrationData Data=initial;public NvStatus Status=NvStatus.Locked;public bool FailUnlock,FailLock,IgnoreWrite,LockAttempt;public int CenterCommands;public Action? RebootHook,UnlockHook,CenterHook;private byte[] command=[];
 public Task SetFeatureAsync(byte id,ReadOnlyMemory<byte> payload,CancellationToken ct){ct.ThrowIfCancellationRequested();command=payload.ToArray();if(id==0x82){CenterCommands++;if(command[0]==2)CenterHook?.Invoke();}if(command.SequenceEqual(new byte[]{1,1}))RebootHook?.Invoke();if(command[0]==12&&command[1]==1&&!IgnoreWrite){var v=new ushort[12];for(int i=0;i<12;i++)v[i]=System.Buffers.Binary.BinaryPrimitives.ReadUInt16LittleEndian(command.AsSpan(2+i*2,2));Data=new(v);}if(command.SequenceEqual(new byte[]{3,2,101,50,64,12})){Status=NvStatus.Unlocked;UnlockHook?.Invoke();if(FailUnlock)throw new IOException("disconnect");}if(command.SequenceEqual(new byte[]{3,1})){LockAttempt=true;if(FailLock)throw new IOException("lock failed");Status=NvStatus.Locked;}return Task.CompletedTask;}
 public Task<byte[]> GetFeatureAsync(byte id,CancellationToken ct){var b=new byte[64];b[0]=id;if(id==0x83){b[1]=1;b[2]=1;b[3]=(byte)(command[0]==2?2:1);}if(id==0x20){System.Text.Encoding.ASCII.GetBytes("Jan 01 2026").CopyTo(b,1);b[24]=2;b[28]=1;}if(id==0x81&&command.SequenceEqual(new byte[]{1,19})){b[1]=1;b[2]=19;b[3]=2;System.Text.Encoding.ASCII.GetBytes("ABC12345678901234").CopyTo(b,4);}if(id==0x81&&command.SequenceEqual(new byte[]{3,3})){b[1]=3;b[2]=3;b[3]=2;b[4]=(byte)(Status==NvStatus.Locked?1:0);}if(id==0x81&&command.SequenceEqual(new byte[]{12,2})){b[1]=12;b[2]=2;b[3]=2;for(int i=0;i<12;i++)System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian(b.AsSpan(4+i*2,2),Data.Values[i]);}return Task.FromResult(b);}
 public async IAsyncEnumerable<byte[]> ReadInputsAsync([System.Runtime.CompilerServices.EnumeratorCancellation]CancellationToken ct){await Task.CompletedTask;yield break;}
 public ValueTask DisposeAsync()=>ValueTask.CompletedTask;
}
sealed class FakeInteraction:ITestInteraction
{
 public bool Rebooting{get;set;}public bool ResetObserved=true;public string LastConfirmation="";
 public TaskCompletionSource<bool>? PendingConfirmation;public Action? ConfirmationHook;public Func<long,GuidedTestResult>? Guided;public Func<TimeSpan,IReadOnlyList<StickSample>>? Fresh;public CalibrationData? ReconnectData;
 public BatteryInfo Battery=>new(100,"USB",false);
 public Task<bool> ConfirmAsync(string message,CancellationToken ct){LastConfirmation=message;ConfirmationHook?.Invoke();return PendingConfirmation?.Task.WaitAsync(ct)??Task.FromResult(true);}
 public Task<GuidedTestResult> GuidedAsync(long generation,Action<string,double> progress,CancellationToken ct)=>Task.FromResult(Guided?.Invoke(generation)??throw new NotImplementedException());
 public Task<RangeCheckResult> RangeAsync(Action<string,double> progress,CancellationToken ct)=>Task.FromResult(new RangeCheckResult(true));
 public Task<IReadOnlyList<StickSample>> FreshAsync(TimeSpan duration,CancellationToken ct)=>Task.FromResult(Fresh?.Invoke(duration)??Enumerable.Range(0,101).Select(i=>new StickSample(TimeSpan.FromSeconds(i*.005),0,0,0,0)).ToArray());
 public Task<Reconnection> ReconnectAsync(ControllerIdentity id,CancellationToken ct)=>Task.FromResult(new Reconnection(new DualSenseController(new FakeHid(ReconnectData??new CalibrationData(Enumerable.Repeat((ushort)32000,12).ToArray()))),ResetObserved));
}
sealed class ManualClock:TimeProvider
{
 private long ticks;public void Advance(TimeSpan elapsed)=>ticks+=elapsed.Ticks;public override long GetTimestamp()=>ticks;public override long TimestampFrequency=>TimeSpan.TicksPerSecond;public override DateTimeOffset GetUtcNow()=>new DateTimeOffset(2026,10,5,0,0,0,TimeSpan.Zero)+TimeSpan.FromTicks(ticks);
}
