using System.Globalization;
namespace DriftLab.Core;
public enum AppLanguage { English,Italian }
// All app-owned messages share this catalog. Select once, before USB work begins.
public static class AppText
{
 public static AppLanguage Language {get;private set;}=AppLanguage.English;
 public static CultureInfo Culture=>CultureInfo.GetCultureInfo(Language==AppLanguage.English?"en-US":"it-IT");
 public static void Select(AppLanguage language)
 {
  if(language is not (AppLanguage.English or AppLanguage.Italian))throw new ArgumentOutOfRangeException(nameof(language));
  Language=language;CultureInfo.CurrentCulture=Culture;CultureInfo.CurrentUICulture=Culture;
  CultureInfo.DefaultThreadCurrentCulture=Culture;CultureInfo.DefaultThreadCurrentUICulture=Culture;
 }
 public static string T(string italian)=>Language==AppLanguage.Italian?italian:English[italian];
 public static string Format(string italian,params object?[] arguments)=>string.Format(Culture,T(italian),arguments);
 private static readonly Dictionary<string,string> English=new(StringComparer.Ordinal)
 {
  ["Il segnale non è stabile"]="The signal is not stable",
  ["Segnale instabile durante il tentativo"]="Unstable signal during the attempt",
  ["Centro non raggiungibile entro i limiti della regolazione"]="The center cannot be reached within the adjustment limits",
  ["Correzione non convergente"]="The correction did not converge",
  ["basso"]="down",
  ["alto"]="up",
  ["destra"]="right",
  ["sinistra"]="left",
  ["Mancato rientro entro 15 secondi: test non valido."]="The stick did not return within 15 seconds: invalid test.",
  ["Movimento o dati insufficienti. Ripeti il ciclo."]="Movement or insufficient data. Repeat the cycle.",
  ["Test completato."]="Test completed.",
  ["Lascia entrambi gli stick liberi per 10 secondi."]="Leave both sticks untouched for 10 seconds.",
  ["Porta lo stick SINISTRO tutto in {0} ({1}/6)."]="Move the LEFT stick fully {0} ({1}/6).",
  ["Rilascia lo stick senza toccarlo."]="Release the stick and keep your hands off it.",
  ["Non toccare gli stick: misuro il rientro per 8 secondi."]="Do not touch the sticks: measuring their return for 8 seconds.",
  ["Servono 12 parametri"]="12 parameters are required",
  ["Solo centro sinistro"]="Only the left-stick center can be adjusted",
  ["Test dopo calibrazione superato. Salvataggio disponibile."]="Post-calibration test passed. Saving is available.",
  ["Calibrazione non verificata: salvataggio disabilitato."]="Calibration not verified: saving is disabled.",
  ["Sconosciuta"]="Unknown",
  ["Report USB inatteso"]="Unexpected USB report",
  ["Controller non connesso"]="Controller not connected",
  ["Acquisizione scaduta o controller scollegato. Test invalidato."]="Acquisition timed out or controller disconnected. Test invalidated.",
  ["Campioni freschi insufficienti"]="Insufficient fresh samples",
  ["Acquisizione terminata"]="Acquisition ended",
  ["Corsa completa: ruota ENTRAMBI gli stick fino ai bordi, poi rilasciali al centro."]="Full range: rotate BOTH sticks to their outer edges, then release them to center.",
  ["Manca la connessione precedente al riavvio"]="The connection from before the reboot is missing",
  ["Controller scollegato"]="Controller disconnected",
  ["Collega un DualSense standard con cavo USB dati"]="Connect a standard DualSense using a USB data cable",
  ["Test reale del rientro dello stick sinistro. Le modifiche automatiche sono temporanee; il salvataggio permanente richiede conferma."]="Real left-stick return test. Automatic changes are temporary; permanent saving requires confirmation.",
  ["Test preciso di entrambi gli stick: centro ±0,78% · oscillazione oltre un passo USB\nRileva deriva lenta, microtremolii, rumore e picchi isolati. Nessun test ancora eseguito.\nUn valore USB varia a passi di 0,78%; lo zero esatto non è rappresentabile in un singolo campione."]="Precision test of both sticks: center ±0.78% · oscillation beyond one USB step\nDetects slow drift, microtremor, noise and isolated spikes. No test has run yet.\nUSB values change in 0.78% steps; exact zero cannot be represented in an individual sample.",
  ["Cerca controller"]="Find controller",
  ["Test e correzione automatica"]="Test and automatic correction",
  ["Salva nel controller"]="Save to controller",
  ["Restore"]="Restore",
  ["Riavvia controller"]="Reboot controller",
  ["Esporta backup"]="Export backup",
  ["Importa backup"]="Import backup",
  ["Annulla test"]="Cancel test",
  ["Conferma operazione"]="Confirm operation",
  ["Salva Restore"]="Save Restore",
  ["Nessun DualSense USB trovato. Usa un cavo dati; chiudi eventuali app che occupano il controller."]="No USB DualSense found. Use a data cable; close apps that may be using the controller.",
  ["Scegli l'interfaccia DualSense"]="Choose the DualSense interface",
  ["Pronto. Premi Test e correzione automatica e segui le istruzioni."]="Ready. Click Test and automatic correction and follow the instructions.",
  ["USB rilevato: monitoraggio disponibile, calibrazione bloccata"]="USB detected: monitoring available, calibration blocked",
  ["Connessione USB non disponibile"]="USB connection unavailable",
  ["{0} · centro SX {1} · DX {2}"]="{0} · center L {1} · R {2}",
  ["Deriva SX {0:0.00}% / DX {1:0.00}% · oscillazione SX {2:0.00}% / DX {3:0.00}% · picco {4:0.00}% · campioni con picchi {5}"]="Drift L {0:0.00}% / R {1:0.00}% · oscillation L {2:0.00}% / R {3:0.00}% · peak {4:0.00}% · spike samples {5}",
  ["Prima: {0}\nDopo: {1}\nValori reali senza filtro. Oscillazione = ampiezza P5–P95; picco = distanza dalla mediana. Alto = Y negativo."]="Before: {0}\nAfter: {1}\nUnfiltered readings. Oscillation = P5–P95 width; peak = distance from the median. Up = negative Y.",
  ["Nessun difetto rilevato"]="No fault detected",
  ["Scostamento stabile"]="Stable offset",
  ["Movimento progressivo"]="Progressive drift",
  ["Rumore significativo"]="Significant noise",
  ["Microtremolio"]="Microtremor",
  ["Picchi intermittenti"]="Intermittent spikes",
  ["Centro dipendente dal rilascio"]="Center depends on release direction",
  ["Test non valido"]="Invalid test",
  ["Operazione annullata. Ripristino temporaneo tentato se necessario."]="Operation cancelled. Temporary rollback attempted if needed.",
  ["Operazione non conclusa"]="Operation not completed",
  ["Nessun backup conservato per questo controller."]="No stored backups for this controller.",
  ["Restore: scegli un backup"]="Restore: choose a backup",
  ["Backup calibrazione JSON|*.json"]="Calibration backup JSON|*.json",
  ["Backup esportato."]="Backup exported.",
  ["Salvataggio permanente in corso: attendi il completamento prima di chiudere."]="Permanent saving in progress: wait for completion before closing.",
  ["Annullamento e ripristino in corso. Chiudi quando l'operazione termina."]="Cancellation and rollback in progress. Close when the operation finishes.",
  ["Seleziona"]="Select",
  ["STICK DESTRO"]="RIGHT STICK",
  ["STICK SINISTRO"]="LEFT STICK",
  ["Nessun dato"]="No data",
  ["Y sinistro · ultimi 12 s · scala ±15% (valori più grandi tagliati solo nel grafico)"]="Left Y · last 12 s · scale ±15% (larger values clipped only in the graph)",
  ["Un'operazione è già in corso"]="An operation is already in progress",
  ["Connessione cambiata: risultato invalidato"]="Connection changed: result invalidated",
  ["Verifica scaduta: serve un nuovo test positivo o un Restore verificato"]="Verification expired: a new passing test or verified Restore is required",
  ["Controller scollegato. Risultati invalidati."]="Controller disconnected. Results invalidated.",
  ["Identità controller cambiata"]="Controller identity changed",
  ["Creo il backup iniziale prima del test."]="Creating the initial backup before the test.",
  ["Test non valido: campioni insufficienti."]="Invalid test: insufficient samples.",
  ["Nessun difetto rilevato nei periodi osservati. Nessuna modifica."]="No fault detected during the observed periods. No changes made.",
  ["Scostamento stabile: tentativo temporaneo del solo centro sinistro."]="Stable offset: temporary adjustment of the left-stick center only.",
  ["Nessun miglioramento stabile. Calibrazione originale ripristinata."]="No stable improvement. Original calibration restored.",
  ["Rilevato tremolio, picchi, centro instabile o un problema anche allo stick destro. La calibrazione non ripara l'usura. Vuoi provare UNA calibrazione temporanea del centro di ENTRAMBI gli stick? Lasciali entrambi liberi."]="Detected tremor, spikes, an unstable center or a problem with the right stick too. Calibration cannot repair wear. Try ONE temporary center calibration of BOTH sticks? Leave both sticks untouched.",
  ["Tentativo non eseguito. Nessuna modifica."]="Attempt not performed. No changes made.",
  ["Ripeto il test completo con gli stessi criteri."]="Repeating the full test using the same criteria.",
  ["Miglioramento parziale"]="Partial improvement",
  ["Nessun miglioramento verificato"]="No verified improvement",
  [". Calibrazione originale ripristinata; salvataggio disabilitato."]=". Original calibration restored; saving disabled.",
  ["Calibrazione cambiata durante la verifica"]="Calibration changed during verification",
  ["Test interrotto. Ripristino temporaneo verificato."]="Test interrupted. Temporary rollback verified.",
  ["Operazione fallita e ripristino NON verificato. Ricollega il controller; nessun salvataggio abilitato."]="Operation failed and rollback NOT verified. Reconnect the controller; saving is not enabled.",
  ["Ripristinare TEMPORANEAMENTE il backup del {0:g}? Non è un reset di fabbrica. Potrebbe riportare il vecchio drift."]="TEMPORARILY restore the backup from {0:g}? This is not a factory reset. It may bring back the old drift.",
  ["Restore temporaneo verificato. Usa Salva Restore per renderlo permanente, oppure Riavvia per scartarlo."]="Temporary Restore verified. Use Save Restore to make it permanent, or Reboot to discard it.",
  ["Serve un test positivo recente o un Restore verificato"]="A recent passing test or verified Restore is required",
  ["Stato batteria anomalo: scrittura bloccata"]="Abnormal battery status: writing blocked",
  ["Salvare il RESTORE nel controller? Il backup può contenere il vecchio drift. "]="Save the RESTORE to the controller? The backup may contain the old drift. ",
  ["Salvare la nuova calibrazione nel controller? "]="Save the new calibration to the controller? ",
  ["Mantieni il cavo USB e la batteria INTERNA collegati. Confermi che l'alimentazione è stabile? Non scollegare o chiudere durante la scrittura."]="Keep the USB cable and the INTERNAL battery connected. Do you confirm the power supply is stable? Do not disconnect or close during writing.",
  ["Dati freschi/alimentazione non validi"]="Invalid fresh data or power status",
  ["Parametri diversi dalla calibrazione verificata"]="Parameters differ from the verified calibration",
  ["Salvataggio permanente in corso. NON scollegare il controller."]="Permanent saving in progress. DO NOT disconnect the controller.",
  ["Memoria bloccata. Riavvio e verifica del salvataggio..."]="Memory locked. Rebooting and verifying the save...",
  ["Riavvio fisico non osservato: salvataggio non verificato"]="Physical reboot not observed: saving not verified",
  ["Rilettura dopo riavvio non corrispondente"]="Readback after reboot does not match",
  ["Salvataggio confermato dopo riavvio e rilettura. Prova ora il controller nel gioco."]="Save confirmed after reboot and readback. Now test the controller in your game.",
  ["Salvataggio INCERTO: non eseguire altre scritture. Ricollega e verifica il controller."]="Save UNCERTAIN: do not perform further writes. Reconnect and check the controller.",
  ["Riavvio: le modifiche temporanee verranno scartate."]="Rebooting: temporary changes will be discarded.",
  ["Riavvio fisico non osservato"]="Physical reboot not observed",
  ["Controller diverso dopo riavvio"]="Different controller after reboot",
  ["Stesso controller riconnesso. Esegui un nuovo test."]="Same controller reconnected. Run a new test.",
  ["Identità firmware non disponibile"]="Firmware identity unavailable",
  ["Firmware troppo vecchio: aggiorna il controller prima della calibrazione"]="Firmware too old: update the controller before calibration",
  ["Risposta seriale inattesa"]="Unexpected serial response",
  ["Seriale non affidabile: modifiche bloccate"]="Unreliable serial number: changes blocked",
  ["Memoria non bloccata: regolazione temporanea vietata"]="Memory not locked: temporary adjustment forbidden",
  ["Rilettura diversa: regolazione non verificata"]="Readback differs: adjustment not verified",
  ["Stato memoria incompatibile"]="Incompatible memory status",
  ["Sblocco memoria non verificato"]="Memory unlock not verified",
  ["Blocco finale memoria non confermato"]="Final memory lock not confirmed",
  ["Blocco finale fallito. Salvataggio incerto; ricollega e verifica il controller."]="Final lock failed. Save uncertain; reconnect and check the controller.",
  ["Salvataggio non concluso; blocco memoria ripristinato."]="Saving did not complete; memory lock restored.",
  ["Memoria non bloccata"]="Memory not locked",
  ["Calibrazione guidata non confermata"]="Guided calibration not confirmed",
  ["Risposta calibrazione inattesa"]="Unexpected calibration response",
  ["Batteria"]="Battery",
  ["In carica USB"]="Charging via USB",
  ["Carica completa"]="Fully charged",
  ["Stato alimentazione anomalo"]="Abnormal power status",
  ["Sessione HID invalidata da un trasferimento interrotto"]="HID session invalidated by an interrupted transfer",
  ["Sessione HID invalidata"]="HID session invalidated",
  ["Ciclo non valido: hai mosso lo stick o mancano campioni. Vuoi ripetere questo ciclo?"]="Invalid cycle: stick movement or missing samples. Repeat this cycle?",
  ["Test interrotto"]="Test interrupted",
  ["Backup corrotto, incompatibile o di un altro controller"]="Backup corrupted, incompatible or from a different controller",
  ["Backup oltre 64 KiB"]="Backup exceeds 64 KiB",
  ["Backup troppo grande"]="Backup too large",
  ["Backup vuoto"]="Empty backup",
  ["Dimensione interfaccia HID inattesa"]="Unexpected HID interface size",
  ["Trasferimento HID precedente ancora in corso"]="A previous HID transfer is still in progress",
  ["Interfaccia controller già aperta"]="Controller interface already open",
  ["Connessione USB non verificata"]="USB connection not verified",
  ["Payload fuori limite HID"]="Payload exceeds the HID limit",
  ["Report non USB: calibrazione bloccata"]="Non-USB report: calibration blocked",
  ["Crediti"]="Credits",
  ["Protocollo: dualshock-tools · the_al"]="Protocol: dualshock-tools · the_al",
  ["Riferimento del protocollo di calibrazione DualSense:\ndualshock-tools · the_al\nLicenza MIT; attribuzione e testo completo in THIRD_PARTY_NOTICES.md.\n\nLa calibrazione può correggere il centro; non ripara un sensore usurato."]="DualSense calibration protocol reference:\ndualshock-tools · the_al\nMIT License; attribution and full text in THIRD_PARTY_NOTICES.md.\n\nCalibration can correct the center; it cannot repair a worn sensor.",
  ["Chiudi"]="Close",
  ["Sì"]="Yes",
  ["No"]="No",
  ["Iniziale"]="Initial",
  ["Salvato"]="Saved",
  ["Ripristinato"]="Restored",
 };
}
